/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    aws_project_region: "us-east-1",
    aws_cognito_identity_pool_id: "us-east-1:f83e600e-2c61-48c3-8f3f-bccc5383efc4",
    aws_cognito_region: "us-east-1",
    aws_user_pools_id: "us-east-1_b0aOIV73z",
    aws_user_pools_web_client_id: "4sr9t2htrv58hmqrrgns3vt2r9",
    aws_appsync_graphqlEndpoint:
      "https://2k7ck56wbfhtrpzuvc66khvrae.appsync-api.us-east-1.amazonaws.com/graphql",
    aws_appsync_region: "us-east-1",
    aws_appsync_authenticationType: "AMAZON_COGNITO_USER_POOLS",
    aws_appsync_apiKey: "da2-cohsbjpnura6fczdyytp5j25vu",
    aws_geo_mapName: "spirits-sit-customer-Here-map",
    aws_geo_mapIndexName: "spirits-sit-customer-Here-singleusePlaceindex",
    aws_s3_imagesUrl: "http://1800spirits-images.s3-website-us-east-1.amazonaws.com",
    firebase_vapidKey:
      "BO7qQGfsWgtkIWL63bK23X5Q-SVNPYwS0SWs1ycEhnwsTZyNhxHgm1NY9YeZVeXUBT4rB_EJzJKdIuxb_GcWdUs",
    stripe_publishable_key:
      "pk_test_51KWLzaKSMMiABBtCCilbLt4xv7wje6bOF6x9qPbHYkQe24nJLhS006unSIMPjoy6lsntNLnEeDRB0GqMgLe7VHaj00R0E1ieAz",
    oauth: {
      domain: "1800spirits-customer-sit.auth.us-east-1.amazoncognito.com",
      scope: ["email", "openid", "profile"],
      redirectSignIn: "spiritscustomerapp://127.0.0.1:19000",
      redirectSignOut: "spiritscustomerapp://127.0.0.1:19000",
      responseType: "token",
    },
    federationTarget: "COGNITO_USER_POOLS",
  }
  
  export default awsmobile
  
